### ISSUE TITLE
Add Role Based Account Management

### ISSUE THREAD

**Issue by luciferw-001** [ChamikaJayarathna/XBlog-Frontend#10]
The current project does not have role based account management, hence the permissions cannot be managed effectively. 

Implement the following, 

- Add New Roles
- Add New Permission Types
- Validate Permissions and Roles at each page where required

**Comment by kgweerawardana** [comment]
Intial Development Began
Need to rectify in each page for permissions
Perform Code Cleanup once the basic code is up and running

**Comment by luciferw-001** [comment]
Handed the task over to you @ChamikaJayarathna
